/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.api;

import com.lcjing.infra.ApiException;
import com.lcjing.infra.model.Account;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    
    /**
     * 根据电话号码禁用用户
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void disableAccountTest() throws ApiException {
        String cellphone = null;
        // String response = api.disableAccount(cellphone);

        // TODO: test validations
    }
    
    /**
     * 用户校验
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountTest() throws ApiException {
        String platformId = null;
        String username = null;
        String password = null;
        // Account response = api.getAccount(platformId, username, password);

        // TODO: test validations
    }
    
    /**
     * 通过账户Id查询账户
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountByCassIdTest() throws ApiException {
        String accountid = null;
        // Account response = api.getAccountByCassId(accountid);

        // TODO: test validations
    }
    
    /**
     * 通过电话号码查询账户
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountByCellphoneTest() throws ApiException {
        String cellphone = null;
        // Account response = api.getAccountByCellphone(cellphone);

        // TODO: test validations
    }
    
    /**
     * 获取一账通accountId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void obtainAccountIdTest() throws ApiException {
        String cellphone = null;
        // String response = api.obtainAccountId(cellphone);

        // TODO: test validations
    }
    
    /**
     * 批量获取一账通accountId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void obtainAccountIdsTest() throws ApiException {
        List<String> cellphones = null;
        // api.obtainAccountIds(cellphones);

        // TODO: test validations
    }
    
}
