/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.api;

import com.lcjing.infra.ApiException;
import com.lcjing.infra.model.ModifyEnterpriseRequest;
import com.lcjing.infra.model.BaseResult;
import com.lcjing.infra.model.RegisterEnterpriseRequest;
import com.lcjing.infra.model.SyncEnterpriseRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnterpriseApi
 */
public class EnterpriseApiTest {

    private final EnterpriseApi api = new EnterpriseApi();

    
    /**
     * 修改企业信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modifyTest() throws ApiException {
        String code = null;
        ModifyEnterpriseRequest request = null;
        // BaseResult response = api.modify(code, request);

        // TODO: test validations
    }
    
    /**
     * 注册企业信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerEnterpriseTest() throws ApiException {
        RegisterEnterpriseRequest request = null;
        // BaseResult response = api.registerEnterprise(request);

        // TODO: test validations
    }
    
    /**
     * 同步企业信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void syncTest() throws ApiException {
        SyncEnterpriseRequest request = null;
        // BaseResult response = api.sync(request);

        // TODO: test validations
    }
    
}
