/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.api;

import com.lcjing.infra.ApiException;
import com.lcjing.infra.model.BaseResult;
import com.lcjing.infra.model.UserEnterpriseRelationsRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RelationApi
 */
public class RelationApiTest {

    private final RelationApi api = new RelationApi();

    
    /**
     * 创建用户与企业关系
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        String userAccountId = null;
        String enterpriseCode = null;
        // BaseResult response = api.create(userAccountId, enterpriseCode);

        // TODO: test validations
    }
    
    /**
     * 查询用户有效的企业关系
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByAccountIdTest() throws ApiException {
        String userAccountId = null;
        // BaseResult response = api.getByAccountId(userAccountId);

        // TODO: test validations
    }
    
    /**
     * 解绑用户与企业关系
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void quitTest() throws ApiException {
        String userAccountId = null;
        String enterpriseCode = null;
        // BaseResult response = api.quit(userAccountId, enterpriseCode);

        // TODO: test validations
    }
    
    /**
     * 批量解绑用户与企业关系
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void quitsTest() throws ApiException {
        UserEnterpriseRelationsRequest request = null;
        // BaseResult response = api.quits(request);

        // TODO: test validations
    }
    
}
