/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDate;


/**
 * 企业扩展信息
 */
@ApiModel(description = "企业扩展信息")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-19T14:41:51.471+08:00")
public class EnterpriseGeoDTO   {
  @SerializedName("enterpriseCode")
  private String enterpriseCode = null;

  @SerializedName("provinceGeoId")
  private String provinceGeoId = null;

  @SerializedName("provinceGeoName")
  private String provinceGeoName = null;

  @SerializedName("cityGeoId")
  private String cityGeoId = null;

  @SerializedName("cityGeoName")
  private String cityGeoName = null;

  @SerializedName("countyGeoId")
  private String countyGeoId = null;

  @SerializedName("countyGeoName")
  private String countyGeoName = null;

  @SerializedName("remark")
  private String remark = null;

  @SerializedName("villageGeoId")
  private String villageGeoId = null;

  @SerializedName("villageGeoName")
  private String villageGeoName = null;

  @SerializedName("longitude")
  private String longitude = null;

  @SerializedName("latitude")
  private String latitude = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("billingAddress")
  private String billingAddress = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("createdStamp")
  private LocalDate createdStamp = null;

  @SerializedName("lastUpdatedStamp")
  private LocalDate lastUpdatedStamp = null;

  public EnterpriseGeoDTO enterpriseCode(String enterpriseCode) {
    this.enterpriseCode = enterpriseCode;
    return this;
  }

   /**
   * 企业代码
   * @return enterpriseCode
  **/
  @ApiModelProperty(example = "null", value = "企业代码")
  public String getEnterpriseCode() {
    return enterpriseCode;
  }

  public void setEnterpriseCode(String enterpriseCode) {
    this.enterpriseCode = enterpriseCode;
  }

  public EnterpriseGeoDTO provinceGeoId(String provinceGeoId) {
    this.provinceGeoId = provinceGeoId;
    return this;
  }

   /**
   * 省份Id
   * @return provinceGeoId
  **/
  @ApiModelProperty(example = "null", value = "省份Id")
  public String getProvinceGeoId() {
    return provinceGeoId;
  }

  public void setProvinceGeoId(String provinceGeoId) {
    this.provinceGeoId = provinceGeoId;
  }

  public EnterpriseGeoDTO provinceGeoName(String provinceGeoName) {
    this.provinceGeoName = provinceGeoName;
    return this;
  }

   /**
   * 省份名称
   * @return provinceGeoName
  **/
  @ApiModelProperty(example = "null", value = "省份名称")
  public String getProvinceGeoName() {
    return provinceGeoName;
  }

  public void setProvinceGeoName(String provinceGeoName) {
    this.provinceGeoName = provinceGeoName;
  }

  public EnterpriseGeoDTO cityGeoId(String cityGeoId) {
    this.cityGeoId = cityGeoId;
    return this;
  }

   /**
   * 地级市Id
   * @return cityGeoId
  **/
  @ApiModelProperty(example = "null", value = "地级市Id")
  public String getCityGeoId() {
    return cityGeoId;
  }

  public void setCityGeoId(String cityGeoId) {
    this.cityGeoId = cityGeoId;
  }

  public EnterpriseGeoDTO cityGeoName(String cityGeoName) {
    this.cityGeoName = cityGeoName;
    return this;
  }

   /**
   * 地级市名称
   * @return cityGeoName
  **/
  @ApiModelProperty(example = "null", value = "地级市名称")
  public String getCityGeoName() {
    return cityGeoName;
  }

  public void setCityGeoName(String cityGeoName) {
    this.cityGeoName = cityGeoName;
  }

  public EnterpriseGeoDTO countyGeoId(String countyGeoId) {
    this.countyGeoId = countyGeoId;
    return this;
  }

   /**
   * 区县Id
   * @return countyGeoId
  **/
  @ApiModelProperty(example = "null", value = "区县Id")
  public String getCountyGeoId() {
    return countyGeoId;
  }

  public void setCountyGeoId(String countyGeoId) {
    this.countyGeoId = countyGeoId;
  }

  public EnterpriseGeoDTO countyGeoName(String countyGeoName) {
    this.countyGeoName = countyGeoName;
    return this;
  }

   /**
   * 区县名称
   * @return countyGeoName
  **/
  @ApiModelProperty(example = "null", value = "区县名称")
  public String getCountyGeoName() {
    return countyGeoName;
  }

  public void setCountyGeoName(String countyGeoName) {
    this.countyGeoName = countyGeoName;
  }

  public EnterpriseGeoDTO remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * 备注
   * @return remark
  **/
  @ApiModelProperty(example = "null", value = "备注")
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public EnterpriseGeoDTO villageGeoId(String villageGeoId) {
    this.villageGeoId = villageGeoId;
    return this;
  }

   /**
   * 街道Id
   * @return villageGeoId
  **/
  @ApiModelProperty(example = "null", value = "街道Id")
  public String getVillageGeoId() {
    return villageGeoId;
  }

  public void setVillageGeoId(String villageGeoId) {
    this.villageGeoId = villageGeoId;
  }

  public EnterpriseGeoDTO villageGeoName(String villageGeoName) {
    this.villageGeoName = villageGeoName;
    return this;
  }

   /**
   * 街道名称
   * @return villageGeoName
  **/
  @ApiModelProperty(example = "null", value = "街道名称")
  public String getVillageGeoName() {
    return villageGeoName;
  }

  public void setVillageGeoName(String villageGeoName) {
    this.villageGeoName = villageGeoName;
  }

  public EnterpriseGeoDTO longitude(String longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * 经度
   * @return longitude
  **/
  @ApiModelProperty(example = "null", value = "经度")
  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  public EnterpriseGeoDTO latitude(String latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * 纬度
   * @return latitude
  **/
  @ApiModelProperty(example = "null", value = "纬度")
  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public EnterpriseGeoDTO address(String address) {
    this.address = address;
    return this;
  }

   /**
   * 企业注册详细地址
   * @return address
  **/
  @ApiModelProperty(example = "null", value = "企业注册详细地址")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public EnterpriseGeoDTO billingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * 开票地址
   * @return billingAddress
  **/
  @ApiModelProperty(example = "null", value = "开票地址")
  public String getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
  }

  public EnterpriseGeoDTO createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * 创建人
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "创建人")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public EnterpriseGeoDTO lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * 修改人
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(example = "null", value = "修改人")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public EnterpriseGeoDTO createdStamp(LocalDate createdStamp) {
    this.createdStamp = createdStamp;
    return this;
  }

   /**
   * 创建时间
   * @return createdStamp
  **/
  @ApiModelProperty(example = "null", value = "创建时间")
  public LocalDate getCreatedStamp() {
    return createdStamp;
  }

  public void setCreatedStamp(LocalDate createdStamp) {
    this.createdStamp = createdStamp;
  }

  public EnterpriseGeoDTO lastUpdatedStamp(LocalDate lastUpdatedStamp) {
    this.lastUpdatedStamp = lastUpdatedStamp;
    return this;
  }

   /**
   * 修改时间
   * @return lastUpdatedStamp
  **/
  @ApiModelProperty(example = "null", value = "修改时间")
  public LocalDate getLastUpdatedStamp() {
    return lastUpdatedStamp;
  }

  public void setLastUpdatedStamp(LocalDate lastUpdatedStamp) {
    this.lastUpdatedStamp = lastUpdatedStamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseGeoDTO enterpriseGeoDTO = (EnterpriseGeoDTO) o;
    return Objects.equals(this.enterpriseCode, enterpriseGeoDTO.enterpriseCode) &&
        Objects.equals(this.provinceGeoId, enterpriseGeoDTO.provinceGeoId) &&
        Objects.equals(this.provinceGeoName, enterpriseGeoDTO.provinceGeoName) &&
        Objects.equals(this.cityGeoId, enterpriseGeoDTO.cityGeoId) &&
        Objects.equals(this.cityGeoName, enterpriseGeoDTO.cityGeoName) &&
        Objects.equals(this.countyGeoId, enterpriseGeoDTO.countyGeoId) &&
        Objects.equals(this.countyGeoName, enterpriseGeoDTO.countyGeoName) &&
        Objects.equals(this.remark, enterpriseGeoDTO.remark) &&
        Objects.equals(this.villageGeoId, enterpriseGeoDTO.villageGeoId) &&
        Objects.equals(this.villageGeoName, enterpriseGeoDTO.villageGeoName) &&
        Objects.equals(this.longitude, enterpriseGeoDTO.longitude) &&
        Objects.equals(this.latitude, enterpriseGeoDTO.latitude) &&
        Objects.equals(this.address, enterpriseGeoDTO.address) &&
        Objects.equals(this.billingAddress, enterpriseGeoDTO.billingAddress) &&
        Objects.equals(this.createdBy, enterpriseGeoDTO.createdBy) &&
        Objects.equals(this.lastUpdatedBy, enterpriseGeoDTO.lastUpdatedBy) &&
        Objects.equals(this.createdStamp, enterpriseGeoDTO.createdStamp) &&
        Objects.equals(this.lastUpdatedStamp, enterpriseGeoDTO.lastUpdatedStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enterpriseCode, provinceGeoId, provinceGeoName, cityGeoId, cityGeoName, countyGeoId, countyGeoName, remark, villageGeoId, villageGeoName, longitude, latitude, address, billingAddress, createdBy, lastUpdatedBy, createdStamp, lastUpdatedStamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseGeoDTO {\n");
    
    sb.append("    enterpriseCode: ").append(toIndentedString(enterpriseCode)).append("\n");
    sb.append("    provinceGeoId: ").append(toIndentedString(provinceGeoId)).append("\n");
    sb.append("    provinceGeoName: ").append(toIndentedString(provinceGeoName)).append("\n");
    sb.append("    cityGeoId: ").append(toIndentedString(cityGeoId)).append("\n");
    sb.append("    cityGeoName: ").append(toIndentedString(cityGeoName)).append("\n");
    sb.append("    countyGeoId: ").append(toIndentedString(countyGeoId)).append("\n");
    sb.append("    countyGeoName: ").append(toIndentedString(countyGeoName)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    villageGeoId: ").append(toIndentedString(villageGeoId)).append("\n");
    sb.append("    villageGeoName: ").append(toIndentedString(villageGeoName)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    createdStamp: ").append(toIndentedString(createdStamp)).append("\n");
    sb.append("    lastUpdatedStamp: ").append(toIndentedString(lastUpdatedStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

