/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ModifyEnterpriseRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-19T14:41:51.471+08:00")
public class ModifyEnterpriseRequest   {
  @SerializedName("enterpriseName")
  private String enterpriseName = null;

  @SerializedName("isIntegration")
  private String isIntegration = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("provinceGeoId")
  private String provinceGeoId = null;

  @SerializedName("provinceGeoName")
  private String provinceGeoName = null;

  @SerializedName("cityGeoId")
  private String cityGeoId = null;

  @SerializedName("cityGeoName")
  private String cityGeoName = null;

  @SerializedName("countyGeoId")
  private String countyGeoId = null;

  @SerializedName("countyGeoName")
  private String countyGeoName = null;

  @SerializedName("remark")
  private String remark = null;

  @SerializedName("villageGeoId")
  private String villageGeoId = null;

  @SerializedName("villageGeoName")
  private String villageGeoName = null;

  @SerializedName("longitude")
  private String longitude = null;

  @SerializedName("latitude")
  private String latitude = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("billingAddress")
  private String billingAddress = null;

  public ModifyEnterpriseRequest enterpriseName(String enterpriseName) {
    this.enterpriseName = enterpriseName;
    return this;
  }

   /**
   * 企业名称
   * @return enterpriseName
  **/
  @ApiModelProperty(example = "null", value = "企业名称")
  public String getEnterpriseName() {
    return enterpriseName;
  }

  public void setEnterpriseName(String enterpriseName) {
    this.enterpriseName = enterpriseName;
  }

  public ModifyEnterpriseRequest isIntegration(String isIntegration) {
    this.isIntegration = isIntegration;
    return this;
  }

   /**
   * 是否三证合一
   * @return isIntegration
  **/
  @ApiModelProperty(example = "null", value = "是否三证合一")
  public String getIsIntegration() {
    return isIntegration;
  }

  public void setIsIntegration(String isIntegration) {
    this.isIntegration = isIntegration;
  }

  public ModifyEnterpriseRequest lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * 修改人
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(example = "null", value = "修改人")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public ModifyEnterpriseRequest provinceGeoId(String provinceGeoId) {
    this.provinceGeoId = provinceGeoId;
    return this;
  }

   /**
   * 省份Id
   * @return provinceGeoId
  **/
  @ApiModelProperty(example = "null", value = "省份Id")
  public String getProvinceGeoId() {
    return provinceGeoId;
  }

  public void setProvinceGeoId(String provinceGeoId) {
    this.provinceGeoId = provinceGeoId;
  }

  public ModifyEnterpriseRequest provinceGeoName(String provinceGeoName) {
    this.provinceGeoName = provinceGeoName;
    return this;
  }

   /**
   * 省份名称
   * @return provinceGeoName
  **/
  @ApiModelProperty(example = "null", value = "省份名称")
  public String getProvinceGeoName() {
    return provinceGeoName;
  }

  public void setProvinceGeoName(String provinceGeoName) {
    this.provinceGeoName = provinceGeoName;
  }

  public ModifyEnterpriseRequest cityGeoId(String cityGeoId) {
    this.cityGeoId = cityGeoId;
    return this;
  }

   /**
   * 地级市Id
   * @return cityGeoId
  **/
  @ApiModelProperty(example = "null", value = "地级市Id")
  public String getCityGeoId() {
    return cityGeoId;
  }

  public void setCityGeoId(String cityGeoId) {
    this.cityGeoId = cityGeoId;
  }

  public ModifyEnterpriseRequest cityGeoName(String cityGeoName) {
    this.cityGeoName = cityGeoName;
    return this;
  }

   /**
   * 地级市名称
   * @return cityGeoName
  **/
  @ApiModelProperty(example = "null", value = "地级市名称")
  public String getCityGeoName() {
    return cityGeoName;
  }

  public void setCityGeoName(String cityGeoName) {
    this.cityGeoName = cityGeoName;
  }

  public ModifyEnterpriseRequest countyGeoId(String countyGeoId) {
    this.countyGeoId = countyGeoId;
    return this;
  }

   /**
   * 区县Id
   * @return countyGeoId
  **/
  @ApiModelProperty(example = "null", value = "区县Id")
  public String getCountyGeoId() {
    return countyGeoId;
  }

  public void setCountyGeoId(String countyGeoId) {
    this.countyGeoId = countyGeoId;
  }

  public ModifyEnterpriseRequest countyGeoName(String countyGeoName) {
    this.countyGeoName = countyGeoName;
    return this;
  }

   /**
   * 区县名称
   * @return countyGeoName
  **/
  @ApiModelProperty(example = "null", value = "区县名称")
  public String getCountyGeoName() {
    return countyGeoName;
  }

  public void setCountyGeoName(String countyGeoName) {
    this.countyGeoName = countyGeoName;
  }

  public ModifyEnterpriseRequest remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * 备注
   * @return remark
  **/
  @ApiModelProperty(example = "null", value = "备注")
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public ModifyEnterpriseRequest villageGeoId(String villageGeoId) {
    this.villageGeoId = villageGeoId;
    return this;
  }

   /**
   * 街道Id
   * @return villageGeoId
  **/
  @ApiModelProperty(example = "null", value = "街道Id")
  public String getVillageGeoId() {
    return villageGeoId;
  }

  public void setVillageGeoId(String villageGeoId) {
    this.villageGeoId = villageGeoId;
  }

  public ModifyEnterpriseRequest villageGeoName(String villageGeoName) {
    this.villageGeoName = villageGeoName;
    return this;
  }

   /**
   * 街道名称
   * @return villageGeoName
  **/
  @ApiModelProperty(example = "null", value = "街道名称")
  public String getVillageGeoName() {
    return villageGeoName;
  }

  public void setVillageGeoName(String villageGeoName) {
    this.villageGeoName = villageGeoName;
  }

  public ModifyEnterpriseRequest longitude(String longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * 经度
   * @return longitude
  **/
  @ApiModelProperty(example = "null", value = "经度")
  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  public ModifyEnterpriseRequest latitude(String latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * 纬度
   * @return latitude
  **/
  @ApiModelProperty(example = "null", value = "纬度")
  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public ModifyEnterpriseRequest address(String address) {
    this.address = address;
    return this;
  }

   /**
   * 企业注册详细地址
   * @return address
  **/
  @ApiModelProperty(example = "null", value = "企业注册详细地址")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ModifyEnterpriseRequest billingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * 开票地址
   * @return billingAddress
  **/
  @ApiModelProperty(example = "null", value = "开票地址")
  public String getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyEnterpriseRequest modifyEnterpriseRequest = (ModifyEnterpriseRequest) o;
    return Objects.equals(this.enterpriseName, modifyEnterpriseRequest.enterpriseName) &&
        Objects.equals(this.isIntegration, modifyEnterpriseRequest.isIntegration) &&
        Objects.equals(this.lastUpdatedBy, modifyEnterpriseRequest.lastUpdatedBy) &&
        Objects.equals(this.provinceGeoId, modifyEnterpriseRequest.provinceGeoId) &&
        Objects.equals(this.provinceGeoName, modifyEnterpriseRequest.provinceGeoName) &&
        Objects.equals(this.cityGeoId, modifyEnterpriseRequest.cityGeoId) &&
        Objects.equals(this.cityGeoName, modifyEnterpriseRequest.cityGeoName) &&
        Objects.equals(this.countyGeoId, modifyEnterpriseRequest.countyGeoId) &&
        Objects.equals(this.countyGeoName, modifyEnterpriseRequest.countyGeoName) &&
        Objects.equals(this.remark, modifyEnterpriseRequest.remark) &&
        Objects.equals(this.villageGeoId, modifyEnterpriseRequest.villageGeoId) &&
        Objects.equals(this.villageGeoName, modifyEnterpriseRequest.villageGeoName) &&
        Objects.equals(this.longitude, modifyEnterpriseRequest.longitude) &&
        Objects.equals(this.latitude, modifyEnterpriseRequest.latitude) &&
        Objects.equals(this.address, modifyEnterpriseRequest.address) &&
        Objects.equals(this.billingAddress, modifyEnterpriseRequest.billingAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enterpriseName, isIntegration, lastUpdatedBy, provinceGeoId, provinceGeoName, cityGeoId, cityGeoName, countyGeoId, countyGeoName, remark, villageGeoId, villageGeoName, longitude, latitude, address, billingAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyEnterpriseRequest {\n");
    
    sb.append("    enterpriseName: ").append(toIndentedString(enterpriseName)).append("\n");
    sb.append("    isIntegration: ").append(toIndentedString(isIntegration)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    provinceGeoId: ").append(toIndentedString(provinceGeoId)).append("\n");
    sb.append("    provinceGeoName: ").append(toIndentedString(provinceGeoName)).append("\n");
    sb.append("    cityGeoId: ").append(toIndentedString(cityGeoId)).append("\n");
    sb.append("    cityGeoName: ").append(toIndentedString(cityGeoName)).append("\n");
    sb.append("    countyGeoId: ").append(toIndentedString(countyGeoId)).append("\n");
    sb.append("    countyGeoName: ").append(toIndentedString(countyGeoName)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    villageGeoId: ").append(toIndentedString(villageGeoId)).append("\n");
    sb.append("    villageGeoName: ").append(toIndentedString(villageGeoName)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

