/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * RegisterEnterpriseRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-19T14:41:51.471+08:00")
public class RegisterEnterpriseRequest   {
  @SerializedName("enterpriseName")
  private String enterpriseName = null;

  @SerializedName("unifiedSocialCreditCode")
  private String unifiedSocialCreditCode = null;

  @SerializedName("regCode")
  private String regCode = null;

  @SerializedName("taxCode")
  private String taxCode = null;

  @SerializedName("orgCode")
  private String orgCode = null;

  @SerializedName("isIntegration")
  private String isIntegration = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("provinceGeoId")
  private String provinceGeoId = null;

  @SerializedName("provinceGeoName")
  private String provinceGeoName = null;

  @SerializedName("cityGeoId")
  private String cityGeoId = null;

  @SerializedName("cityGeoName")
  private String cityGeoName = null;

  @SerializedName("countyGeoId")
  private String countyGeoId = null;

  @SerializedName("countyGeoName")
  private String countyGeoName = null;

  @SerializedName("remark")
  private String remark = null;

  @SerializedName("villageGeoId")
  private String villageGeoId = null;

  @SerializedName("villageGeoName")
  private String villageGeoName = null;

  @SerializedName("longitude")
  private String longitude = null;

  @SerializedName("latitude")
  private String latitude = null;

  @SerializedName("address")
  private String address = null;

  public RegisterEnterpriseRequest enterpriseName(String enterpriseName) {
    this.enterpriseName = enterpriseName;
    return this;
  }

   /**
   * 企业名称
   * @return enterpriseName
  **/
  @ApiModelProperty(example = "null", value = "企业名称")
  public String getEnterpriseName() {
    return enterpriseName;
  }

  public void setEnterpriseName(String enterpriseName) {
    this.enterpriseName = enterpriseName;
  }

  public RegisterEnterpriseRequest unifiedSocialCreditCode(String unifiedSocialCreditCode) {
    this.unifiedSocialCreditCode = unifiedSocialCreditCode;
    return this;
  }

   /**
   * 统一社会信用代码
   * @return unifiedSocialCreditCode
  **/
  @ApiModelProperty(example = "null", value = "统一社会信用代码")
  public String getUnifiedSocialCreditCode() {
    return unifiedSocialCreditCode;
  }

  public void setUnifiedSocialCreditCode(String unifiedSocialCreditCode) {
    this.unifiedSocialCreditCode = unifiedSocialCreditCode;
  }

  public RegisterEnterpriseRequest regCode(String regCode) {
    this.regCode = regCode;
    return this;
  }

   /**
   * 营业执照号
   * @return regCode
  **/
  @ApiModelProperty(example = "null", value = "营业执照号")
  public String getRegCode() {
    return regCode;
  }

  public void setRegCode(String regCode) {
    this.regCode = regCode;
  }

  public RegisterEnterpriseRequest taxCode(String taxCode) {
    this.taxCode = taxCode;
    return this;
  }

   /**
   * 税务登记证号
   * @return taxCode
  **/
  @ApiModelProperty(example = "null", value = "税务登记证号")
  public String getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(String taxCode) {
    this.taxCode = taxCode;
  }

  public RegisterEnterpriseRequest orgCode(String orgCode) {
    this.orgCode = orgCode;
    return this;
  }

   /**
   * 组织机构代码
   * @return orgCode
  **/
  @ApiModelProperty(example = "null", value = "组织机构代码")
  public String getOrgCode() {
    return orgCode;
  }

  public void setOrgCode(String orgCode) {
    this.orgCode = orgCode;
  }

  public RegisterEnterpriseRequest isIntegration(String isIntegration) {
    this.isIntegration = isIntegration;
    return this;
  }

   /**
   * 是否三证合一
   * @return isIntegration
  **/
  @ApiModelProperty(example = "null", value = "是否三证合一")
  public String getIsIntegration() {
    return isIntegration;
  }

  public void setIsIntegration(String isIntegration) {
    this.isIntegration = isIntegration;
  }

  public RegisterEnterpriseRequest createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * 创建人
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "创建人")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public RegisterEnterpriseRequest lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * 修改人
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(example = "null", value = "修改人")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public RegisterEnterpriseRequest provinceGeoId(String provinceGeoId) {
    this.provinceGeoId = provinceGeoId;
    return this;
  }

   /**
   * 省份Id
   * @return provinceGeoId
  **/
  @ApiModelProperty(example = "null", value = "省份Id")
  public String getProvinceGeoId() {
    return provinceGeoId;
  }

  public void setProvinceGeoId(String provinceGeoId) {
    this.provinceGeoId = provinceGeoId;
  }

  public RegisterEnterpriseRequest provinceGeoName(String provinceGeoName) {
    this.provinceGeoName = provinceGeoName;
    return this;
  }

   /**
   * 省份名称
   * @return provinceGeoName
  **/
  @ApiModelProperty(example = "null", value = "省份名称")
  public String getProvinceGeoName() {
    return provinceGeoName;
  }

  public void setProvinceGeoName(String provinceGeoName) {
    this.provinceGeoName = provinceGeoName;
  }

  public RegisterEnterpriseRequest cityGeoId(String cityGeoId) {
    this.cityGeoId = cityGeoId;
    return this;
  }

   /**
   * 地级市Id
   * @return cityGeoId
  **/
  @ApiModelProperty(example = "null", value = "地级市Id")
  public String getCityGeoId() {
    return cityGeoId;
  }

  public void setCityGeoId(String cityGeoId) {
    this.cityGeoId = cityGeoId;
  }

  public RegisterEnterpriseRequest cityGeoName(String cityGeoName) {
    this.cityGeoName = cityGeoName;
    return this;
  }

   /**
   * 地级市名称
   * @return cityGeoName
  **/
  @ApiModelProperty(example = "null", value = "地级市名称")
  public String getCityGeoName() {
    return cityGeoName;
  }

  public void setCityGeoName(String cityGeoName) {
    this.cityGeoName = cityGeoName;
  }

  public RegisterEnterpriseRequest countyGeoId(String countyGeoId) {
    this.countyGeoId = countyGeoId;
    return this;
  }

   /**
   * 区县Id
   * @return countyGeoId
  **/
  @ApiModelProperty(example = "null", value = "区县Id")
  public String getCountyGeoId() {
    return countyGeoId;
  }

  public void setCountyGeoId(String countyGeoId) {
    this.countyGeoId = countyGeoId;
  }

  public RegisterEnterpriseRequest countyGeoName(String countyGeoName) {
    this.countyGeoName = countyGeoName;
    return this;
  }

   /**
   * 区县名称
   * @return countyGeoName
  **/
  @ApiModelProperty(example = "null", value = "区县名称")
  public String getCountyGeoName() {
    return countyGeoName;
  }

  public void setCountyGeoName(String countyGeoName) {
    this.countyGeoName = countyGeoName;
  }

  public RegisterEnterpriseRequest remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * 备注
   * @return remark
  **/
  @ApiModelProperty(example = "null", value = "备注")
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public RegisterEnterpriseRequest villageGeoId(String villageGeoId) {
    this.villageGeoId = villageGeoId;
    return this;
  }

   /**
   * 街道Id
   * @return villageGeoId
  **/
  @ApiModelProperty(example = "null", value = "街道Id")
  public String getVillageGeoId() {
    return villageGeoId;
  }

  public void setVillageGeoId(String villageGeoId) {
    this.villageGeoId = villageGeoId;
  }

  public RegisterEnterpriseRequest villageGeoName(String villageGeoName) {
    this.villageGeoName = villageGeoName;
    return this;
  }

   /**
   * 街道名称
   * @return villageGeoName
  **/
  @ApiModelProperty(example = "null", value = "街道名称")
  public String getVillageGeoName() {
    return villageGeoName;
  }

  public void setVillageGeoName(String villageGeoName) {
    this.villageGeoName = villageGeoName;
  }

  public RegisterEnterpriseRequest longitude(String longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * 经度
   * @return longitude
  **/
  @ApiModelProperty(example = "null", value = "经度")
  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  public RegisterEnterpriseRequest latitude(String latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * 纬度
   * @return latitude
  **/
  @ApiModelProperty(example = "null", value = "纬度")
  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public RegisterEnterpriseRequest address(String address) {
    this.address = address;
    return this;
  }

   /**
   * 企业注册详细地址
   * @return address
  **/
  @ApiModelProperty(example = "null", value = "企业注册详细地址")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisterEnterpriseRequest registerEnterpriseRequest = (RegisterEnterpriseRequest) o;
    return Objects.equals(this.enterpriseName, registerEnterpriseRequest.enterpriseName) &&
        Objects.equals(this.unifiedSocialCreditCode, registerEnterpriseRequest.unifiedSocialCreditCode) &&
        Objects.equals(this.regCode, registerEnterpriseRequest.regCode) &&
        Objects.equals(this.taxCode, registerEnterpriseRequest.taxCode) &&
        Objects.equals(this.orgCode, registerEnterpriseRequest.orgCode) &&
        Objects.equals(this.isIntegration, registerEnterpriseRequest.isIntegration) &&
        Objects.equals(this.createdBy, registerEnterpriseRequest.createdBy) &&
        Objects.equals(this.lastUpdatedBy, registerEnterpriseRequest.lastUpdatedBy) &&
        Objects.equals(this.provinceGeoId, registerEnterpriseRequest.provinceGeoId) &&
        Objects.equals(this.provinceGeoName, registerEnterpriseRequest.provinceGeoName) &&
        Objects.equals(this.cityGeoId, registerEnterpriseRequest.cityGeoId) &&
        Objects.equals(this.cityGeoName, registerEnterpriseRequest.cityGeoName) &&
        Objects.equals(this.countyGeoId, registerEnterpriseRequest.countyGeoId) &&
        Objects.equals(this.countyGeoName, registerEnterpriseRequest.countyGeoName) &&
        Objects.equals(this.remark, registerEnterpriseRequest.remark) &&
        Objects.equals(this.villageGeoId, registerEnterpriseRequest.villageGeoId) &&
        Objects.equals(this.villageGeoName, registerEnterpriseRequest.villageGeoName) &&
        Objects.equals(this.longitude, registerEnterpriseRequest.longitude) &&
        Objects.equals(this.latitude, registerEnterpriseRequest.latitude) &&
        Objects.equals(this.address, registerEnterpriseRequest.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enterpriseName, unifiedSocialCreditCode, regCode, taxCode, orgCode, isIntegration, createdBy, lastUpdatedBy, provinceGeoId, provinceGeoName, cityGeoId, cityGeoName, countyGeoId, countyGeoName, remark, villageGeoId, villageGeoName, longitude, latitude, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisterEnterpriseRequest {\n");
    
    sb.append("    enterpriseName: ").append(toIndentedString(enterpriseName)).append("\n");
    sb.append("    unifiedSocialCreditCode: ").append(toIndentedString(unifiedSocialCreditCode)).append("\n");
    sb.append("    regCode: ").append(toIndentedString(regCode)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    orgCode: ").append(toIndentedString(orgCode)).append("\n");
    sb.append("    isIntegration: ").append(toIndentedString(isIntegration)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    provinceGeoId: ").append(toIndentedString(provinceGeoId)).append("\n");
    sb.append("    provinceGeoName: ").append(toIndentedString(provinceGeoName)).append("\n");
    sb.append("    cityGeoId: ").append(toIndentedString(cityGeoId)).append("\n");
    sb.append("    cityGeoName: ").append(toIndentedString(cityGeoName)).append("\n");
    sb.append("    countyGeoId: ").append(toIndentedString(countyGeoId)).append("\n");
    sb.append("    countyGeoName: ").append(toIndentedString(countyGeoName)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    villageGeoId: ").append(toIndentedString(villageGeoId)).append("\n");
    sb.append("    villageGeoName: ").append(toIndentedString(villageGeoName)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

