/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.lcjing.infra.model.EnterpriseDTO;
import com.lcjing.infra.model.EnterpriseGeoDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SyncEnterpriseRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-19T14:41:51.471+08:00")
public class SyncEnterpriseRequest   {
  @SerializedName("enterpriseDTO")
  private EnterpriseDTO enterpriseDTO = null;

  @SerializedName("enterpriseGeoDTO")
  private EnterpriseGeoDTO enterpriseGeoDTO = null;

  public SyncEnterpriseRequest enterpriseDTO(EnterpriseDTO enterpriseDTO) {
    this.enterpriseDTO = enterpriseDTO;
    return this;
  }

   /**
   * Get enterpriseDTO
   * @return enterpriseDTO
  **/
  @ApiModelProperty(example = "null", value = "")
  public EnterpriseDTO getEnterpriseDTO() {
    return enterpriseDTO;
  }

  public void setEnterpriseDTO(EnterpriseDTO enterpriseDTO) {
    this.enterpriseDTO = enterpriseDTO;
  }

  public SyncEnterpriseRequest enterpriseGeoDTO(EnterpriseGeoDTO enterpriseGeoDTO) {
    this.enterpriseGeoDTO = enterpriseGeoDTO;
    return this;
  }

   /**
   * Get enterpriseGeoDTO
   * @return enterpriseGeoDTO
  **/
  @ApiModelProperty(example = "null", value = "")
  public EnterpriseGeoDTO getEnterpriseGeoDTO() {
    return enterpriseGeoDTO;
  }

  public void setEnterpriseGeoDTO(EnterpriseGeoDTO enterpriseGeoDTO) {
    this.enterpriseGeoDTO = enterpriseGeoDTO;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncEnterpriseRequest syncEnterpriseRequest = (SyncEnterpriseRequest) o;
    return Objects.equals(this.enterpriseDTO, syncEnterpriseRequest.enterpriseDTO) &&
        Objects.equals(this.enterpriseGeoDTO, syncEnterpriseRequest.enterpriseGeoDTO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enterpriseDTO, enterpriseGeoDTO);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncEnterpriseRequest {\n");
    
    sb.append("    enterpriseDTO: ").append(toIndentedString(enterpriseDTO)).append("\n");
    sb.append("    enterpriseGeoDTO: ").append(toIndentedString(enterpriseGeoDTO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

