/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * UserEnterpriseRelationsRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-19T14:41:51.471+08:00")
public class UserEnterpriseRelationsRequest   {
  @SerializedName("userAccountIds")
  private List<String> userAccountIds = new ArrayList<String>();

  @SerializedName("enterpriseCode")
  private String enterpriseCode = null;

  @SerializedName("operator")
  private String operator = null;

  public UserEnterpriseRelationsRequest userAccountIds(List<String> userAccountIds) {
    this.userAccountIds = userAccountIds;
    return this;
  }

  public UserEnterpriseRelationsRequest addUserAccountIdsItem(String userAccountIdsItem) {
    this.userAccountIds.add(userAccountIdsItem);
    return this;
  }

   /**
   * 账户Id集合
   * @return userAccountIds
  **/
  @ApiModelProperty(example = "null", value = "账户Id集合")
  public List<String> getUserAccountIds() {
    return userAccountIds;
  }

  public void setUserAccountIds(List<String> userAccountIds) {
    this.userAccountIds = userAccountIds;
  }

  public UserEnterpriseRelationsRequest enterpriseCode(String enterpriseCode) {
    this.enterpriseCode = enterpriseCode;
    return this;
  }

   /**
   * 企业代码
   * @return enterpriseCode
  **/
  @ApiModelProperty(example = "null", value = "企业代码")
  public String getEnterpriseCode() {
    return enterpriseCode;
  }

  public void setEnterpriseCode(String enterpriseCode) {
    this.enterpriseCode = enterpriseCode;
  }

  public UserEnterpriseRelationsRequest operator(String operator) {
    this.operator = operator;
    return this;
  }

   /**
   * 操作人
   * @return operator
  **/
  @ApiModelProperty(example = "null", value = "操作人")
  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEnterpriseRelationsRequest userEnterpriseRelationsRequest = (UserEnterpriseRelationsRequest) o;
    return Objects.equals(this.userAccountIds, userEnterpriseRelationsRequest.userAccountIds) &&
        Objects.equals(this.enterpriseCode, userEnterpriseRelationsRequest.enterpriseCode) &&
        Objects.equals(this.operator, userEnterpriseRelationsRequest.operator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userAccountIds, enterpriseCode, operator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEnterpriseRelationsRequest {\n");
    
    sb.append("    userAccountIds: ").append(toIndentedString(userAccountIds)).append("\n");
    sb.append("    enterpriseCode: ").append(toIndentedString(enterpriseCode)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

