/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * UserDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-19T14:41:51.471+08:00")
public class UserDTO   {
  @SerializedName("accountId")
  private String accountId = null;

  @SerializedName("userLoginId")
  private String userLoginId = null;

  @SerializedName("platformId")
  private Integer platformId = null;

  @SerializedName("userLoginAccount")
  private String userLoginAccount = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("userCellphone")
  private String userCellphone = null;

  @SerializedName("registerPlatform")
  private String registerPlatform = null;

  @SerializedName("registerTerminal")
  private String registerTerminal = null;

  @SerializedName("isEnabled")
  private Boolean isEnabled = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("createdStamp")
  private String createdStamp = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("lastUpdatedStamp")
  private String lastUpdatedStamp = null;

  public UserDTO accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * 用户 id
   * @return accountId
  **/
  @ApiModelProperty(example = "null", value = "用户 id")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public UserDTO userLoginId(String userLoginId) {
    this.userLoginId = userLoginId;
    return this;
  }

   /**
   * 用户登录 id
   * @return userLoginId
  **/
  @ApiModelProperty(example = "null", value = "用户登录 id")
  public String getUserLoginId() {
    return userLoginId;
  }

  public void setUserLoginId(String userLoginId) {
    this.userLoginId = userLoginId;
  }

  public UserDTO platformId(Integer platformId) {
    this.platformId = platformId;
    return this;
  }

   /**
   * 注册平台
   * @return platformId
  **/
  @ApiModelProperty(example = "null", value = "注册平台")
  public Integer getPlatformId() {
    return platformId;
  }

  public void setPlatformId(Integer platformId) {
    this.platformId = platformId;
  }

  public UserDTO userLoginAccount(String userLoginAccount) {
    this.userLoginAccount = userLoginAccount;
    return this;
  }

   /**
   * 用户账号
   * @return userLoginAccount
  **/
  @ApiModelProperty(example = "null", value = "用户账号")
  public String getUserLoginAccount() {
    return userLoginAccount;
  }

  public void setUserLoginAccount(String userLoginAccount) {
    this.userLoginAccount = userLoginAccount;
  }

  public UserDTO userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * 用户姓名
   * @return userName
  **/
  @ApiModelProperty(example = "null", value = "用户姓名")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UserDTO password(String password) {
    this.password = password;
    return this;
  }

   /**
   * 用户密码
   * @return password
  **/
  @ApiModelProperty(example = "null", value = "用户密码")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserDTO userCellphone(String userCellphone) {
    this.userCellphone = userCellphone;
    return this;
  }

   /**
   * 用户手机号
   * @return userCellphone
  **/
  @ApiModelProperty(example = "null", value = "用户手机号")
  public String getUserCellphone() {
    return userCellphone;
  }

  public void setUserCellphone(String userCellphone) {
    this.userCellphone = userCellphone;
  }

  public UserDTO registerPlatform(String registerPlatform) {
    this.registerPlatform = registerPlatform;
    return this;
  }

   /**
   * 用户注册来源
   * @return registerPlatform
  **/
  @ApiModelProperty(example = "null", value = "用户注册来源")
  public String getRegisterPlatform() {
    return registerPlatform;
  }

  public void setRegisterPlatform(String registerPlatform) {
    this.registerPlatform = registerPlatform;
  }

  public UserDTO registerTerminal(String registerTerminal) {
    this.registerTerminal = registerTerminal;
    return this;
  }

   /**
   * 用户注册名称
   * @return registerTerminal
  **/
  @ApiModelProperty(example = "null", value = "用户注册名称")
  public String getRegisterTerminal() {
    return registerTerminal;
  }

  public void setRegisterTerminal(String registerTerminal) {
    this.registerTerminal = registerTerminal;
  }

  public UserDTO isEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * 账号是否可用
   * @return isEnabled
  **/
  @ApiModelProperty(example = "null", value = "账号是否可用")
  public Boolean getIsEnabled() {
    return isEnabled;
  }

  public void setIsEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }

  public UserDTO createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * 创建人
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "创建人")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public UserDTO createdStamp(String createdStamp) {
    this.createdStamp = createdStamp;
    return this;
  }

   /**
   * 创建时间
   * @return createdStamp
  **/
  @ApiModelProperty(example = "null", value = "创建时间")
  public String getCreatedStamp() {
    return createdStamp;
  }

  public void setCreatedStamp(String createdStamp) {
    this.createdStamp = createdStamp;
  }

  public UserDTO lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * 更新人
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(example = "null", value = "更新人")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public UserDTO lastUpdatedStamp(String lastUpdatedStamp) {
    this.lastUpdatedStamp = lastUpdatedStamp;
    return this;
  }

   /**
   * 更新时间
   * @return lastUpdatedStamp
  **/
  @ApiModelProperty(example = "null", value = "更新时间")
  public String getLastUpdatedStamp() {
    return lastUpdatedStamp;
  }

  public void setLastUpdatedStamp(String lastUpdatedStamp) {
    this.lastUpdatedStamp = lastUpdatedStamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDTO userDTO = (UserDTO) o;
    return Objects.equals(this.accountId, userDTO.accountId) &&
        Objects.equals(this.userLoginId, userDTO.userLoginId) &&
        Objects.equals(this.platformId, userDTO.platformId) &&
        Objects.equals(this.userLoginAccount, userDTO.userLoginAccount) &&
        Objects.equals(this.userName, userDTO.userName) &&
        Objects.equals(this.password, userDTO.password) &&
        Objects.equals(this.userCellphone, userDTO.userCellphone) &&
        Objects.equals(this.registerPlatform, userDTO.registerPlatform) &&
        Objects.equals(this.registerTerminal, userDTO.registerTerminal) &&
        Objects.equals(this.isEnabled, userDTO.isEnabled) &&
        Objects.equals(this.createdBy, userDTO.createdBy) &&
        Objects.equals(this.createdStamp, userDTO.createdStamp) &&
        Objects.equals(this.lastUpdatedBy, userDTO.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedStamp, userDTO.lastUpdatedStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, userLoginId, platformId, userLoginAccount, userName, password, userCellphone, registerPlatform, registerTerminal, isEnabled, createdBy, createdStamp, lastUpdatedBy, lastUpdatedStamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDTO {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    userLoginId: ").append(toIndentedString(userLoginId)).append("\n");
    sb.append("    platformId: ").append(toIndentedString(platformId)).append("\n");
    sb.append("    userLoginAccount: ").append(toIndentedString(userLoginAccount)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    userCellphone: ").append(toIndentedString(userCellphone)).append("\n");
    sb.append("    registerPlatform: ").append(toIndentedString(registerPlatform)).append("\n");
    sb.append("    registerTerminal: ").append(toIndentedString(registerTerminal)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdStamp: ").append(toIndentedString(createdStamp)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedStamp: ").append(toIndentedString(lastUpdatedStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

