/**
 * union-service
 * 一账通API接口
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.lcjing.infra.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * UserDeleteAccountRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-19T14:41:51.471+08:00")
public class UserDeleteAccountRequest   {
  @SerializedName("platformId")
  private Integer platformId = null;

  @SerializedName("loginId")
  private String loginId = null;

  public UserDeleteAccountRequest platformId(Integer platformId) {
    this.platformId = platformId;
    return this;
  }

   /**
   * 平台Id
   * @return platformId
  **/
  @ApiModelProperty(example = "null", value = "平台Id")
  public Integer getPlatformId() {
    return platformId;
  }

  public void setPlatformId(Integer platformId) {
    this.platformId = platformId;
  }

  public UserDeleteAccountRequest loginId(String loginId) {
    this.loginId = loginId;
    return this;
  }

   /**
   * 登录Id
   * @return loginId
  **/
  @ApiModelProperty(example = "null", value = "登录Id")
  public String getLoginId() {
    return loginId;
  }

  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDeleteAccountRequest userDeleteAccountRequest = (UserDeleteAccountRequest) o;
    return Objects.equals(this.platformId, userDeleteAccountRequest.platformId) &&
        Objects.equals(this.loginId, userDeleteAccountRequest.loginId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platformId, loginId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDeleteAccountRequest {\n");
    
    sb.append("    platformId: ").append(toIndentedString(platformId)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

